import moduleId from '../constants/module-id';

export default {
  FETCH_PRODUCTS: `${moduleId}/FETCH_PRODUCTS`,
  FETCH_PRODUCTS_SUCCESS: `${moduleId}/FETCH_PRODUCTS_SUCCESS`,
  FETCH_PRODUCTS_ERROR: `${moduleId}/FETCH_PRODUCTS_ERROR`,
  TOGGLE_PRODUCT_STATE: `${moduleId}/TOGGLE_PRODUCT_STATE`,
  REMOVE_PRODUCT: `${moduleId}/REMOVE_PRODUCT`,
  ADD_PRODUCT: `${moduleId}/ADD_PRODUCT`,
  UPDATE_PRODUCT_TITLE: `${moduleId}/UPDATE_PRODUCT_TITLE`,
};
